/*TABELA USUÁRIOS*/
IF OBJECT_ID ('Usuarios', 'U') IS NOT NULL
	DROP TABLE Usuarios;

CREATE TABLE Usuarios(
	ID_Usuario INT NOT NULL IDENTITY(1,1),	
	NM_Usuario VARCHAR(150) NOT NULL,
	NM_Senha VARCHAR(32) NOT NULL
)
GO
ALTER TABLE Usuarios ADD CONSTRAINT PK_USUARIOS PRIMARY KEY (ID_Usuario)

/*TABELA AMIGOS*/
IF OBJECT_ID ('Amigos', 'U') IS NOT NULL
	DROP TABLE Amigos;

CREATE TABLE Amigos(
	ID_Amigo INT NOT NULL IDENTITY(1,1),
	ID_Usuario INT NOT NULL,
	NM_Amigo VARCHAR(150) NOT NULL,
	NR_CEP CHAR(9) NOT NULL,
	NR_Lat DECIMAL(24,12) NOT NULL,
	NR_Lng DECIMAL(24,12) NOT NULL
)
GO
ALTER TABLE Amigos ADD CONSTRAINT PK_AMIGOS PRIMARY KEY (ID_Amigo)
GO
ALTER TABLE Amigos ADD CONSTRAINT FK_Amigos_Usuarios FOREIGN KEY (ID_Usuario) REFERENCES Usuarios (ID_Usuario)

/*TABELA CALCULOHISTORICOLOG*/
IF OBJECT_ID ('CalculoHistoricoLog', 'U') IS NOT NULL
	DROP TABLE CalculoHistoricoLog;

CREATE TABLE CalculoHistoricoLog(
	ID_CalculoHistoricoLog INT NOT NULL IDENTITY(1,1),
	ID_Usuario INT NOT NULL,
	NM_Calculo VARCHAR(MAX) NOT NULL,
	DT_Criacao DATETIME NOT NULL
)
GO
ALTER TABLE CalculoHistoricoLog ADD CONSTRAINT PK_ID_CALCULOHISTORICOLOG PRIMARY KEY (ID_CalculoHistoricoLog)
GO
ALTER TABLE CalculoHistoricoLog ADD CONSTRAINT FK_CalculoHistoricoLog_Usuarios FOREIGN KEY (ID_Usuario) REFERENCES Usuarios (ID_Usuario)