//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Amigos
    {
        public int ID_Amigo { get; set; }
        public int ID_Usuario { get; set; }
        public string NM_Amigo { get; set; }
        public string NR_CEP { get; set; }
        public decimal NR_Lat { get; set; }
        public decimal NR_Lng { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
