//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalculoHistoricoLog
    {
        public int ID_CalculoHistoricoLog { get; set; }
        public int ID_Usuario { get; set; }
        public string NM_Calculo { get; set; }
        public System.DateTime DT_Criacao { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
